### ISSUE TITLE
JackMidi.eventWrite question

### ISSUE THREAD

**Issue by sc3sc3** [jaudiolibs/jnajack#13]
I have a question.
https://stackoverflow.com/questions/62418077/jackmidi-eventwrite-time-parameter 
I'm certain I fail crucial understanding, but how can I send midiMessages created in a Java/Swing application to another MidiPort(software/hardware) via Jack ?
I can't figure out how I can process those messages on the JackProcessCallback
https://github.com/sc3sc3/MidiJnaJackTest (example to show my issue ) 
I'm writing to the output port with JackMidi.eventWrite but 1 of 2 things happen, 
the midiMessage arrives eternally repeated in a loop or the message does not arrive at all.
Thanks for your time and your work. Regards.

**Comment by neilcsmith-net** [comment]
I think it's sample offset from the start of the current buffer IIRC - see https://jackaudio.org/api/group__MIDIAPI.html#gaa25503c07ac3c2ed62d79be9c25d42ed  Not looked at this feature for a long time.  So 0 should be fine I think.

Is the example at https://github.com/jaudiolibs/examples/blob/master/src/main/java/org/jaudiolibs/examples/MidiThru.java working for you?

**Comment by sc3sc3** [comment]
The MidiThru example is working for me.
If I use 0 in the example I post here https://github.com/sc3sc3/MidiJnaJackTest
then the messages are repeated eternally.

**Comment by neilcsmith-net** [comment]
That makes sense. Think you should be using the process callback to clear the MIDI buffer and writing a MIDI event if there is one. Otherwise you'll get the same MIDI buffer every callback, so you're continuously outputting the same event(s).

**Comment by sc3sc3** [comment]
Thanks for the pointer. 0 as time works indeed. I solved the issue by adding messages to a queue
and processing the queue in the process callback:

	public boolean process(JackClient client, int frame) {
		try {
			JackMidi.clearBuffer(this.outputPort);
		} catch (JackException e) {
			e.printStackTrace();
		}
		while (messageQueue.size() > 0) {
			ShortMessage msg = messageQueue.remove();
			try {
				JackMidi.eventWrite(this.outputPort, 0, msg.getMessage(), msg.getLength());
			} catch (JackException e) {
				e.printStackTrace();
				continue;
			}
		}
		return true;
	}
	public void processMidiMessage(ShortMessage shortMessage) {
		messageQueue.add(shortMessage);
	}
