### ISSUE TITLE
How do I access jack_is_realtime?

### ISSUE THREAD

**Issue by markjfisher** [jaudiolibs/jnajack#16]
I thought I'd have a go at converting Catia to Kotlin, and am using your jnajack to interface.

I've just started, and have some basics working:

```kotlin
    val jack = Jack.getInstance()
    val options = EnumSet.of(JackOptions.JackNoStartServer)
    val status = EnumSet.noneOf(JackStatus::class.java)
    val client = jack.openClient("jacKot test", options, status)

    val bs = client.bufferSize
    val sr = client.sampleRate
//    val rt = client. ... no method here for is_real_time
    println("bs: $bs, sr: $sr")

```

I'm trying to get the is_realtime value from jack, but can't seem to find an exposed method that allows me to get the value.

I was hoping to find it on `client.realTime` (which would invoke client.isRealTime() in java).

I can see it in JackLibraryDirect, but JackLib isn't exposed on the client, so I can't call it. I was expecting a wrapper function like `JackClient.getBufferSize()` and `JackClient.getSampleRate()` (which I'm using in the above code), but can't see an equivalent `JackClient.isRealTime()` to use.

**Comment by neilcsmith-net** [comment]
Looks like this was never exposed in the API. Not everything is. Happy to accept a PR with this one. Could look at rolling a new release.

**Comment by markjfisher** [comment]
Cheers, I'll have a play over the weekend and submit a PR

**Comment by markjfisher** [comment]
I think this is done now.
