### ISSUE TITLE
failure attempt to obtain midi data from jack

### ISSUE THREAD

**Issue by nybbs2003** [jaudiolibs/jnajack#4]
when I try to read midi data using audioserver-jack, by calling jack_midi_event_get , I can't read, and the method returns -115.

**Comment by neilcsmith-net** [comment]
Thanks for the report. Why are you using jack_midi_event_get directly?  Have you seen the example at https://github.com/jaudiolibs/examples/blob/master/src/main/java/org/jaudiolibs/examples/MidiThru.java ?

What OS are you on?  Does MIDI work in JACK otherwise?  Can you share the code that you're using to call this function?  Are you doing it outside of a process callback?

**Comment by nybbs2003** [comment]
OS: Ubuntu 17.04 Kylin, on bare machine(not inside virtual machine)
JACK and MIDI both work on other applications
I call static methods of JackMidi, much the same way as the example
I do the retrival inside the process callback.

**Comment by nybbs2003** [comment]
code available here [https://git.oschina.net/nybbs2003/audioservers/commit/6a0adf5e67bea3146cf615fc7c6dcdc46350b0f0](https://git.oschina.net/nybbs2003/audioservers/commit/6a0adf5e67bea3146cf615fc7c6dcdc46350b0f0)

**Comment by neilcsmith-net** [comment]
The call to read the MIDI events should be inside the process callback from JACK, but if you're doing it inside processBuffers() you should be OK there.  I'm not sure why you're hacking the audio server to do this though?  Either set up a separate MIDI client - they will be called in sync.  Or, you should be able to add MIDI ports inside client.configure() - audioConfiguration.find(JackClient.class) should give you the JACK client.
 
Does the example actually work for you?  Let's start with that and work from there!

**Comment by nybbs2003** [comment]
after trying out the MidiThru example, and compare with the original way I use the interface, I found that the problem is not how I call the method, but the amount of the to process it. If not quick enough, throws "ENOBUF"
