### ISSUE TITLE
JackPort.getBuffer() vs JackPort.getFloatBuffer()

### ISSUE THREAD

**Issue by piegamesde** [jaudiolibs/jnajack#9]
I have a few questions concerning the `JackPort.getBuffer()` documentation:

- What data does it contain?
- If it contains audio data, how is the data encoded?
- Why is `getFloatBuffer()` faster/"more efficient"?
- By how much? Is it still better than raw bytes even if I have to convert the floats back to bytes?

**Comment by neilcsmith-net** [comment]
That mostly comes down to one question actually! :smile:  `JackPort` caches the underlying `ByteBuffer` until the pointer changes.  It also caches a `FloatBuffer` which is equivalent to calling `ByteBuffer::asFloatBuffer`.  If you call `JackPort.getBuffer().asFloatBuffer()` you'll get exactly the same result, except that you'll create _a lot_ of short-lasting `FloatBuffer`, and therefore unnecessary overhead / garbage.

The audio is normalised (-1 .. 1) 32-bit floating point data, which is the format that JACK uses.

The caching code is at - https://github.com/jaudiolibs/jnajack/blob/master/src/main/java/org/jaudiolibs/jnajack/JackClient.java#L777

**Comment by piegamesde** [comment]
Thank you, that helps a lot. I think this information could be mentioned in the `asFloatBuffer()` documentation.
